server:
  port: 8089
  tomcat:
    threads:
      max: 600
      min-spare: 50
    accept-count: 500
    accesslog:
      enabled: true
      directory: /opt/server/SecKill/tomasslog
      pattern: '%h %l %u %t "%r" %s %b %D'

datasource:
  url: 192.168.127.131/seckill

spring:
  redis:
    host: 192.168.127.131
    database: 1
    port: 6379
    jedis:
      pool:
        max-active: 50
        min-idle: 20
  datasource:
    druid:
      url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      username: root
      password: 123456

rocketmq:
  name-server: 192.168.127.131:9876
  producer:
    group: test-sotck_group
  consumer:
    group: stock_consumter_group

mybatis: # 指定别名设置的包为所有entity
  type-aliases-package: com.huakai.controller.dto
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml

