server:
  port: 8081
  tomcat:
    threads:
      max: 600
      min-spare: 50
    accept-count: 500

datasource:
  url: localhost:3306/seckill

spring:
  datasource:
    druid:
      url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      username: root
      password: 123456

mybatis: # 指定别名设置的包为所有entity
  type-aliases-package: com.huakai.controller.dto
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml

