package com.huakai.mapper;

import com.huakai.mapper.dataobject.UserPasswordDO;

public interface UserPasswordDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Mon Aug 30 14:58:59 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Mon Aug 30 14:58:59 CST 2021
     */
    int insert(UserPasswordDO record);

    /**
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Mon Aug 30 14:58:59 CST 2021
     */
    int insertSelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Mon Aug 30 14:58:59 CST 2021
     */
    UserPasswordDO selectByPrimaryKey(Integer id);

    String getPasswordByUid(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Mon Aug 30 14:58:59 CST 2021
     */
    int updateByPrimaryKeySelective(UserPasswordDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_password
     *
     * @mbggenerated Mon Aug 30 14:58:59 CST 2021
     */
    int updateByPrimaryKey(UserPasswordDO record);
}