package com.huakai.mapper.dataobject;

import java.io.Serializable;

public class SequenceDO implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.name
     *
     * @mbggenerated Thu Sep 02 15:45:31 CST 2021
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.current_value
     *
     * @mbggenerated Thu Sep 02 15:45:31 CST 2021
     */
    private Integer currentValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.setp
     *
     * @mbggenerated Thu Sep 02 15:45:31 CST 2021
     */
    private Integer step;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sequence_info
     *
     * @mbggenerated Thu Sep 02 15:45:31 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.name
     *
     * @return the value of sequence_info.name
     *
     * @mbggenerated Thu Sep 02 15:45:31 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.name
     *
     * @param name the value for sequence_info.name
     *
     * @mbggenerated Thu Sep 02 15:45:31 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.current_value
     *
     * @return the value of sequence_info.current_value
     *
     * @mbggenerated Thu Sep 02 15:45:31 CST 2021
     */
    public Integer getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.current_value
     *
     * @param currentValue the value for sequence_info.current_value
     *
     * @mbggenerated Thu Sep 02 15:45:31 CST 2021
     */
    public void setCurrentValue(Integer currentValue) {
        this.currentValue = currentValue;
    }


    public Integer getStep() {
        return step;
    }

    public void setStep(Integer step) {
        this.step = step;
    }
}